### ISSUE TITLE
Get-ITGlueConfigurationInterfaces doesn't work

### ISSUE THREAD

**Issue by kamfaima** [itglue/powershellwrapper#105] opened 2020-08-06 02:41 UTC
**Steps to reproduce**

Simply typing `Get-ITGlueConfigurationInterfaces` returns an error "`Get-ITGlueConfigurationInterfaces: Response status code does not indicate success: 404 (Not Found).`"

**Expected behavior**

I'd expect a list of all configuration interfaces to be returned. All other IT Glue `Get-` functions/cmdlets work fine.

**Actual behavior**

```
PS /Users/kfm/Dropbox/Scripts> Get-ITGlueConfigurationInterfaces

Get-ITGlueConfigurationInterfaces: Response status code does not indicate success: 404 (Not Found).
```

**Screenshots**

![image](https://user-images.githubusercontent.com/23546392/89484288-86f46b00-d7e1-11ea-85a8-0cd1f070b194.png)

**Environment**

Please share additional details about your environment. Version information for:
* PowerShell Core 7.0.3
* ITGlueAPI 2.0.9 (installed from PowerShell Gallery https://www.powershellgallery.com/packages/ITGlueAPI/2.0.9)
* Operating System - macOS 10.15.6

**Comment by ecspresso** [comment] 2020-08-06 06:28
https://api.itglue.com/developer#configuration-interfaces

Both `index` and `show` path requires an id, I do not think the API allows just retrieving configuration interfaces. Unless I am wrong, the correct solution would be to make `$conf_id` mandatory.

**Comment by ecspresso** [comment] 2020-08-06 06:59
@kamfaima I created a PR to fix the issue (and some other issues I found) to make it work as intended.

**Comment by kamfaima** [comment] 2020-08-06 08:19
> https://api.itglue.com/developer#configuration-interfaces
> 
> Both `index` and `show` path requires an id, I do not think the API allows just retrieving configuration interfaces. Unless I am wrong, the correct solution would be to make `$conf_id` mandatory.

Happy to be wrong of course, but right now there appears to be no way to retrieve a configuration interface - not via API, nor via the GUI nor is it something I can extract from hovering over some element in the GUI when viewing the configuration which has the configuration interface "attached" to it.

Shouldn't a call to `Get-Something` not require any mandatory parameters? If there was a mandatory parameter (e.g. id) then you would get into a chicken and egg scenario where you wouldn't be able to get the object(s) and its details without first knowing the id of the object.

Once the user knows the id (from an initial `Get-Something` with no parameters) then if they wanted to retrieve just that object, they can use `-id 452` as a parameter, e.g. `Get-Something -id 452`.

**Comment by ecspresso** [comment] 2020-08-06 10:15
> Shouldn't a call to `Get-Something` not require any mandatory parameters? If there was a mandatory parameter (e.g. id) then you would get into a chicken and egg scenario where you wouldn't be able to get the object(s) and its details without first knowing the id of the object.

I agree that it would be ideal to just run `Get-Something` without parameters, but that is not how IT Glue decided to make their API. If you know the configuration, you can go the `index` route of `GET /configurations/:conf_id/relationships/configuration_interfaces` and get all configuration interfaces for one configuration. But there is no endpoint for `GET /configuration_interfaces`.

`conf_id` is a required parameter for the `index` route and `id` for `show`. As this is just a wrapper for the API, the module is meant to behave as the API is documented.

**Comment by kamfaima** [comment] 2020-08-07 01:33
Fair enough, I see what you mean. Thanks for continuing to support the ITG PowerShell module, it's much appreciated! 👏

**Comment by CalebAlbers** [comment] 2021-01-30 20:31
@ecspresso is spot on. Additionally, I just merged his PR relating to it. I'll be pushing a new version of the package soon after I finish a few other PRs.

If you want to get all configuration interfaces at a given organization, you will need to call `Get-ITGlueConfigurations` with the given org ID and then loop over every configuration returned and call the `Get-ITGlueConfigurationInterfaces` cmdlet.

**Closed by CalebAlbers** 2021-01-30 20:31 UTC
